from __future__ import annotations

from typing import Any

from loguru import logger
from sqlalchemy import text
from sqlalchemy.exc import DatabaseError

from brimley import BrimleyContext, on_startup


def _is_name_already_used_error(exc: Exception) -> bool:
    return "ORA-00955" in str(exc)


def _execute_ddl(connection: Any, statement: str) -> None:
    try:
        connection.execute(text(statement))
    except DatabaseError as exc:
        if _is_name_already_used_error(exc):
            return
        raise


@on_startup
def initialize_oracle_demo_schema(ctx: BrimleyContext) -> None:
    """Create and seed the Oracle demo schema when the app starts."""

    logger.info("Starting Oracle demo schema initialization on app startup")

    engine = ctx.databases["default"]

    with engine.begin() as connection:
        _execute_ddl(
            connection,
            """
            CREATE TABLE brimley_demo_customers (
                customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR2(255) NOT NULL UNIQUE,
                full_name VARCHAR2(255) NOT NULL,
                status VARCHAR2(32) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            )
            """,
        )
        _execute_ddl(
            connection,
            """
            CREATE TABLE brimley_demo_startup_events (
                event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_name VARCHAR2(128) NOT NULL,
                details VARCHAR2(4000),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            )
            """,
        )

        existing_customer_count = connection.execute(
            text("SELECT COUNT(*) FROM brimley_demo_customers")
        ).scalar_one()

        if existing_customer_count == 0:
            connection.execute(
                text(
                    """
                    INSERT INTO brimley_demo_customers (email, full_name, status)
                    VALUES (:email, :full_name, :status)
                    """
                ),
                [
                    {
                        "email": "ada@example.com",
                        "full_name": "Ada Lovelace",
                        "status": "active",
                    },
                    {
                        "email": "grace@example.com",
                        "full_name": "Grace Hopper",
                        "status": "active",
                    },
                    {
                        "email": "linus@example.com",
                        "full_name": "Linus Torvalds",
                        "status": "trial",
                    },
                ],
            )

        connection.execute(
            text(
                """
                INSERT INTO brimley_demo_startup_events (event_name, details)
                VALUES (:event_name, :details)
                """
            ),
            {
                "event_name": "schema_initialized",
                "details": "Brimley startup hook ensured Oracle demo tables exist.",
            },
        )

    logger.info("Oracle example schema initialization complete")